ekiosk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include


urlpatterns = [
    
    #path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.productlist, name='product_list'),
    path('postad/', views.postad, name='postad'),
    path('edititem/<slug:product_slug>/', views.edititemview, name='edit_item'),
    path('<slug:category_slug>/', views.productlist, name='product_list_category'),
    path('detail/<slug:product_slug>/', views.productdetail, name='product_detail')
]  

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.

class Product(models.Model):

    CONDITION_TYPE = (
        ("New", "New"),
        ("Used", "Used"),
        ("Slightly Used", "Slightly Used")
    )

    REGION = (
        ("Ahafo Region", "Ahafo Region"),
        ("Ashante Region", "Ashante Region"),
        ("Bono Region", "Bono Region"),
        ("Bono East Region", "Bono East Region"),
        ("Central Region", "Central Region"),
        ("Eastern Region", "Eastern Treson"),
        ("Greater Accra", "Greater Accra"),
        ("Northern REgion", "Northern Region"),
        ("North East", "North East"),
        ("Oti Region", "Oti Region"),
        ("Savannah Region", "Savannah Region"),
        ("Upper East Region", "Upper East Region"),
        ("Upper West Region", "Upper West Region"),
        ("Volta Region", "Volta Region"),
        ("Western Region", "Western Region"),
        ("Western North", "Western North")
    )

    title = models.CharField(max_length=100)
    owner = models.ForeignKey(User , on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null = True)
    brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, null = True, blank=True )
    description = models.TextField(max_length=500)
    condition = models.CharField(max_length=100, choices=CONDITION_TYPE, default="New")
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='main_products/', blank=True, null=True)
    phone = models.CharField(max_length=10, default=None)
    region = models.CharField(choices=REGION, max_length=50)
    date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, null=True)

    #image = ProcessedImageField(upload_to='main_products/', processors=[ResizeToFill(100,100)], format='JPEG', options={'quality': 60}, blank=True, null=True)

    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(100,100)], format='JPEG', options={'quality': 60})

    class Meta:
        ordering = ('-date',)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/', blank=True, null=True)

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category/', blank=True, null=True)

    slug = models.SlugField(blank=True, null=True) 
    
    def save(self, *args, **kwargs):
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name


class Brand(models.Model):
    brand_name = models.CharField(max_length=50) 

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'
        
    def __str__(self):
        return self.brand_name

product/forms.py
from .models import Product, ProductImages
from django import forms

class Sellform(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'category', 'brand', 'description', 
        'condition', 'price', 'image', 'phone', 'region',]

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, ProductImages, Category
from django.core.paginator import Paginator
from django.http import Http404
from django.db.models import Count
from django.db.models import Q 
from django.contrib.auth.decorators import login_required
from .forms import Sellform
# Create your views here.


def productlist(request, category_slug=None):
    category = None
    productlist = Product.objects.all()
    categorylist = Category.objects.annotate(total_product=Count('product'))
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        productlist = productlist.filter(category=category)

    search_query = request.GET.get('q')
    if search_query:
        productlist = productlist.filter(
            Q(title__icontains = search_query) |
            Q(description__icontains = search_query) |
            Q(condition__icontains = search_query) |
            Q(brand__brand_name__icontains = search_query) |
            Q(category__category_name__icontains = search_query) 
        )

    paginator = Paginator(productlist, 10)
    page = request.GET.get('page')
    productlist = paginator.get_page(page)
    template = 'product/product_list.html'

    context = {'product_list':productlist, 'category_list':categorylist, 'category':category }
    return render(request,  template, context)


def productdetail(request, product_slug):
    print(product_slug)
    productdetail = get_object_or_404(Product, slug=product_slug)
    productimages = ProductImages.objects.filter(product=productdetail)
    template = 'product/product_detail.html'
    context = {'product_detail':productdetail,'product_images' : productimages}
    return render(request, template, context)    

@login_required
def postad(request):
    if request.method == 'POST':
        form = Sellform(data=request.POST, files=request.FILES)
        if form.is_valid():
            newproduct = form.save(commit=False)
            newproduct.owner = request.user
            newproduct.save()
            return redirect('accounts:dashboard')
    else:
        form = Sellform()
    return render(request, 'product/postad.html',{'form':form})



@login_required
def edititemview(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    if request.user != product.owner:
        return Http404()
    if request.method == 'POST':
        form = Sellform(data=request.POST, files=request.FILES, instance=product)
        if form.is_valid():
            newproduct = form.save(commit=False)
            newproduct.owner = request.user
            newproduct.save()
            return redirect('accounts:dashboard')
    else:
        form = Sellform(instance=product)
    return render(request, 'product/postad.html',{'form':form})

product/templates/product/postad.html
{% load bootstrap4 %}
{% include 'navbar.html' %}
{% load static %}



<!DOCTYPE html>
<html lang="en">

<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>eKiosk | Post Ad </title>
</head>

<body>

        <br>


        <div class="container">
                <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                                <div id="postadform">
                                        <span class="postad">Post Ad</span>
                                        <form method="POST" enctype="multipart/form-data" class="form">
                                                {% csrf_token %}
                                                {% bootstrap_form form %}
                                                {% buttons %}
                                                <input type="submit" class="btn btn-info" value="Post Ad">
                                                {% endbuttons %}
                                        </form>
                                </div>
                        </div>
                        <div class="col-md-3"></div>
                </div>
        </div>
        <br>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>

</html>

product/templates/product/product_detail.html
{% extends 'base.html' %}


{% block content %}



{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

<br>

<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{% url 'products:product_list' %}">All Ads</a></li>
        {% if category%}
        <li class="breadcrumb-item active">{{category}} </li>
        {% endif %}
    </ol>
</nav>


<br>

<div id="prod_detail" class="container">
    <div class="row">


        <div class="col-md-5">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                        <div class="carousel-item active">
                     {% if product_detail.image %}
                        <img class="d-block" src="{{ product_detail.image.url }}"
                            style=" object-fit: cover;  max-height: 50vh; min-height: 50vh; margin: 0 auto;">
                            {% endif %}
                       
                    </div>
                    {% for image in product_detail.productimages_set.all %}

                    <div class="carousel-item">
                        <img class="d-block"
                            style=" object-fit: cover;  max-height: 50vh;min-height: 50vh; margin: 0 auto;"
                            src="{{ image.image.url }}" alt="Product image">
                    </div>
                    {% endfor %}

                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon  bg-dark" aria-hidden="true"></span>
                    <span class="sr-only bg-dark">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon  bg-dark" aria-hidden="true"></span>
                    <span class="sr-only  bg-dark">Next</span>
                </a>
            </div>

        </div>

        <div class="col-md-4">
            <h2>{{product_detail.title}} </h2>
            <img src="{% static 'img/stars.png' %}" alt="img not found" class="stars">
            <p class="price">Gh₵ {{product_detail.price}} </p>
            <p> <b>Description: </b> {{product_detail.description}} </p>
            <p> <b>Condition: </b> {{product_detail.condition}} </p>
            <p> <b>Brand: </b> {{product_detail.brand}} </p>

            <p><b> Posted by:</b> {{product_detail.owner}}</p>
            <p>Added on: {{product_detail.date}}</p>
        </div>


        <div class="col-md-3">
            <div class="card w-100 text-center">
                <div class="card-header">
                    <h4 class="card-title">Contact Seller</h4>
                </div>
                <ul class="list-group list-group-flush text-justify pl-2"> <br>

                    <h4 class="card-title"> Name: {{ product_detail.owner}}</h4>
                    <h4 class="card-text"> <i class="fa fa-phone pr-2"></i>{{ product_detail.phone }}</h4>
                    <h4 class="card-title">{{ product_detail.region}}</h4> 
                    <br>
                </ul>
            </div>



        </div>
    </div>
</div>

<br>


{% endblock content %}

product/templates/product/product_list.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">



<br>


<!-- all category -->
<div class="card">
    <div id="cardbody" class="card-body">

        <h4>Select Category and find a perfect item </h4>

        {% for category in category_list%}

        <b id="catlist">
            <a href="{% url 'products:product_list_category' category.slug %}"> {{category}}</a>
            <spann class="num-of-adds">( {{category.total_product}} )</spann>
        </b>

        {% endfor %}

    </div>
</div>

<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'products:product_list'%}">All Ads</a></li>
        {% if category%}
        <li class="breadcrumb-item active">{{category}} </li>
        {% endif %}
    </ol>
</nav>

<br>
<!-- end  category list -->


<!-- search form -->
<div class="row">
    <div class="col-md">
        <form class="header-search-form" method="GET" action="{% url 'products:product_list'%}">
            <input id="searchinput" name="q" type="text" placeholder="Search ....">
            <input id="searchbutton" type="button" class="btn btn-info" type="submit" value="Search">
        </form>
        <br>
        <br>
    </div>
</div>
<!-- end of search form -->

<!-- itmes -->

<div class="row">
    <div class="col-md-8">
        {% for product in product_list %}
        <div class="container-box">
            <a id="cardd" href="{% url 'products:product_detail' product.slug %}">
                <div class="container-prodlisting">
                    <div class="image--2hizm">
                        <img class="image-product"
                            src="{% if product.image_thumbnail %}{{ product.image_thumbnail.url }}{% else %}{% endif %}"
                            alt="img not found">
                    </div>
                    <div id="prod-text" class="contents">
                        <span> <b> {{product.title}} </b></span>
                        <div>
                            <div></div>
                            <div><strong id="prodprice">GH₵ {{product.price}}</strong></div>
                            <div><span>{{ product.category}}, {{ product.brand}} </span></div>
                            <div> {{ product.date.date }} </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% empty %}
        <h1>There are no Items...</h2>
            <a href="{% url 'products:postad' %}"> <input type="submit" class="btn btn-dark" value="Post Ad"></a>
            {% endfor %}
    </div>

    <div class="col-md-4">
        <h4>Filter by Price</h4>
    </div>

</div>

<br>

{% if product_list.has_other_pages %}
<ul class="pagination pagination-sm">

    {% if product_list.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ product_list.previous_page_number }}">Prev</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#"></a></li>
    {% endif %}


    {% for pages in product_list.paginator.page_range %}
    {% if product_list.number == pages %}
    <li class="page-item "><a class="page-link" href="#">{{pages}}</a></li>
    {% else %}
    <li class="page-item "><a class="page-link" href="?page={{pages}}">{{pages}}</a></li>
    {% endif %}
    {% endfor %}


    {% if product_list.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#"></a></li>
    {% endif %}

</ul>
{% endif %}

</div>

<!-- end items -->


{% endblock content %}

product/templates/product/sellitem.html
{% load bootstrap4 %}
{% include 'navbar.html' %}
{% load static %}

<link rel="icon" type="image/png" href="{% static 'loginstatic/images/icons/favicon.ico' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css"
        href="{% static 'loginstatic/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css"
        href="{% static 'loginstatic/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/vendor/animate/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/vendor/css-hamburgers/hamburgers.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/vendor/animsition/css/animsition.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/vendor/select2/select2.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/vendor/daterangepicker/daterangepicker.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'loginstatic/css/main.css' %}">

</head>

<body>

        <div class="limiter">
                <div class="container-login100">
                        <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">

                                <span class="login100-form-title p-b-32">
                                        Post Ad
                                </span>

                                <form method="POST" enctype="multipart/form-data" class="form">
                                        {% csrf_token %}
                                        {% bootstrap_form form %}

                                        {% buttons %}
                                        <input type="submit" class="btn btn-primary" value="Post Ad">
                                        {% endbuttons %}


                                </form>
                        </div>
                </div>
        </div>


        <div id="dropDownSelect1"></div>

        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/vendor/animsition/js/animsition.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/vendor/bootstrap/js/popper.js' %}"></script>
        <script src="{% static 'loginstatic/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/vendor/select2/select2.min.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/vendor/daterangepicker/moment.min.js' %}"></script>
        <script src="{% static 'loginstatic/vendor/daterangepicker/daterangepicker.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/vendor/countdowntime/countdowntime.js' %}"></script>
        <!--===============================================================================================-->
        <script src="{% static 'loginstatic/js/main.js' %}"></script>

</body>

</html>