accounts/urls.py
from django.urls import path
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from . import views
#from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name="register"),
    path('editprofile/', views.editprofile, name="editprofile"),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset-done'),
]  

ekiosk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include


urlpatterns = [
    
    #path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.productlist, name='product_list'),
    path('postad/', views.postad, name='postad'),
    path('edititem/<slug:product_slug>/', views.edititemview, name='edit_item'),
    path('<slug:category_slug>/', views.productlist, name='product_list_category'),
    path('detail/<slug:product_slug>/', views.productdetail, name='product_detail')
]  

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.scss' %}">
  <link rel="stylesheet" href="{% static 'css/all.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">


  <title>eKioskgh | Home </title>

</head>

<body class="container">

  <!--::header::-->
  <nav class="navbar navbar-dark bg-info">
    <img id="logo" src="" alt="">
    <a class="navbar-brand" href="{% url 'products:product_list' %}">eKioskgh</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'products:product_list' %}">Home <span class="sr-only"> (current) </span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:postad' %}">Post Ad</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:dashboard' %}">My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>

        {% endif %}

      </ul>
    </div>
  </nav>
  <!--::header ending::-->

  <div id="main_body" class="container">


    {% block content %}

    {% endblock %}

    <br>
    <br>
    <br>


  </div>


  <!--footer-->
  <div id="footer" class="footer-about">
    <div class="footer">

      <div id="footer_about" class="row">

        <div class="container">
          <p class="text-center">
          </p>
        </div>

      </div>

      <div class="row">
        <div class="col-md-4">
          <h5 class="info">Category</h5>
          <ul>
            <li>Electronics</li>
            <li>Automobile</li>
            <li>Clothing</li>
            <li>Jobs</li>
            <li>Mobile</li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5 class="info">Company</h5>
          <ul>
            <li>About</li>
            <li>News</li>
            <li>FAQ</li>
            <li>Contact</li>
          </ul>
        </div>
        <div class="col-md-4">

          <h5 class="info">Safety Measures</h5>
          <ul>
            <li>Some measures here</li>
            <li>Some measures here</li>
            <li>Some measures here</li>
            <li>Some measures here</li>
          </ul>
        </div>
      </div>
    </div>




    <br>

    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">

          <h5 class="text-center info">About</h5>

          <div class="col-md6 text-justify">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero corporis fugiat sed, totam ad commodi iste
            voluptatibus. Maxime obcaecati in sit impedit illo a? Nobis culpa accusantium nisi ratione officiis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod reiciendis impedit sint, ullam numquam
            tempore ea labore odit excepturi optio? Sit itaque placeat a magnam suscipit et sequi rem cupiditate.
          </div>

        </div>
      </div>
    </div>


    <br>



    <div class="container">
      <div class="row">
        <div class="col-md-4 text-justify">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor itaque perferendis inventore beatae velit
          doloribus ut? Tempora ad voluptatum ipsam iusto atque provident officia ut nam aperiam quam? Aperiam, aut.
        </div>
        <div class="col-md-4 text-center">
          <div class="lp-item">
            <div class="lp-thumb set-bg"> <img class="rounded w-25" src="{% static 'img/profile.jpg' %}"
                alt="not found"> </div>
            <div class="lp-content">
              <h6>Who I am</h6>
              <span>Oct 21, 2018</span>
              <a href="#" class="readmore">Read More</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 text-justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maxime deleniti reprehenderit facere omnis ea
          expedita iste labore nihil animi molestias sed perferendis asperiores mollitia minus aliquid consequatur,
          itaque dolorem esse!
        </div>
      </div>
    </div>

    <div id="social_media" class="row">
      <div class="container">
        <div class="social-links">
          <a href="https://wa.me/+233243186008"><i id="favi" class="fab fa-whatsapp"></i><span id="favit">whatsapp</span></a>
          <a href=""><i id="favi" class="fab fa-instagram"></i><span id="favit">instagram</span></a>
          <a href=""><i id="favi" class="fab fa-facebook"></i><span id="favit">facebook</span></a>
          <a href=""><i id="favi" class="fab fa-twitter"></i><span id="favit">twitter</span></a>
        </div>

      </div>
    </div>



    <div id="fotcopy" class="container">
      <hr>
      <h6> @Copyright eKioskgh 2020 </h6>
    </div>
  </div>
  </div>
  <!--footer ending -->

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/carosel.html
{% load static %}


<!--carosel-->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'img/banner2.png' %}" alt="First slide">
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>


<!--carosel ending-->

templates/navbar.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.scss' %}">
<link rel="stylesheet" href="{% static 'css/all.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<!--::header::-->
<div class="container">
  <nav class="navbar navbar-dark bg-info">
    <img id="logo" src="" alt="">
    <a class="navbar-brand" href="{% url 'products:product_list' %}">eKiosk</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'products:product_list' %}">Home <span class="sr-only"> (current) </span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:postad' %}">Post Ad</a>
        </li>
        {% if request.user.is_authenticated %}
  
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:dashboard' %}">My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
  
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
  
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
  
        {% endif %}
  
      </ul>
    </div>
  </nav>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--::header ending::-->